name: Integration Test | Build Packer

# on:
#   push:
#     branches:
#       - main

on:
  pull_request:
    branches:
      - main

jobs:
  build_packer_workflow:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      PORT: ${{ secrets.PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      DROP_DB: ${{ secrets.DROP_DB}}
      TOPIC_VERIFY_EMAIL: ${{ secrets.TOPIC_VERIFY_EMAIL }}
      VERIFY_EMAIL_EXPIRY_MILLISECONDS: ${{ secrets.VERIFY_EMAIL_EXPIRY_MILLISECONDS }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setting up Postgres
      run: |
        sudo systemctl start postgresql.service

        sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_NAME }};"
        sudo -u postgres psql -c "CREATE USER ${{ secrets.DB_USERNAME }} WITH PASSWORD '${{ secrets.DB_PASSWORD }}';"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.DB_NAME }} TO ${{ secrets.DB_USERNAME }};"
    
    - name: Setup Logger Directory
      run: |
          sudo mkdir /var/log/csye6225
          echo "Logger directory created at /var/log/csye6225"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Deleting node_modules
      run: rm -r node_modules

    - name: Zipping webapp artifact
      run: cd ../ && zip -r webapp.zip webapp && cd - && cp ../webapp.zip .

    - name: Installing Packer
      run: sudo apt install -y packer
    
    - name: GCP Authentication
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: GCloud Info
      run: gcloud info

    - name: Setup 'packer'
      uses: hashicorp/setup-packer@main
      with:
        version: '1.10.1'

    - name: Packer Init
      run: packer init ./packer

    - name: Step 04 - Checking Packer Format
      run: packer fmt -check ./packer
    
    - name: Step 05 - Validating Packer
      run: packer validate ./packer

    - name: Packer Build
      run: packer build -var 'proj_id=${{ secrets.GCP_PROJ_ID }}' -var 'db_username=${{ secrets.DB_USERNAME }}' -var 'db_password=${{ secrets.DB_PASSWORD }}' -var 'db_name=${{ secrets.DB_NAME }}' ./packer

    - name: Create new Instance Template version
      run: |
        template_name=${{ secrets.NEW_INSTANCE_TEMPLATE_NAME }}
        old_instance_template_name=$(gcloud compute instance-templates list --sort-by=creationTimestamp --format="value(name)" --limit=1)
        region_url=$(gcloud compute instance-templates describe ${old_instance_template_name} --region=${{ secrets.PROJECT_REGION }} --format="value(region)")
        region=$(basename $region_url)
        machine_type=$(gcloud compute instance-templates describe ${old_instance_template_name} --region=${region} --format="value(properties.machineType)")
        network=$(gcloud compute instance-templates describe ${old_instance_template_name} --region=${region} --format="value(properties.networkInterfaces.network)")
        subnetwork=$(gcloud compute instance-templates describe ${old_instance_template_name} --region=${region} --format="value(properties.networkInterfaces.subnetwork)")
        latest_image_name=$(gcloud compute images list --filter="family:${{ secrets.CUSTOM_IMAGE_FAMILY }}" --sort-by=~creationTimestamp --format="value(name)" --limit=1)
        latest_image_link=$(gcloud compute images describe ${latest_image_name} --format="value(selfLink)")
        boot_disk_kms_key=$(gcloud compute instance-templates describe ${old_instance_template_name} --region=${region} --format="value(properties.disks.diskEncryptionKey.kmsKeyName)")
        disk_size=$(gcloud compute instance-templates describe ${old_instance_template_name} --region=${region} --format="value(properties.disks.initializeParams.diskSizeGb)")
        disk_type=$(gcloud compute instance-templates describe ${old_instance_template_name} --region=${region} --format="value(properties.disks.initializeParams.diskType)")
        labels=$(gcloud compute instance-templates describe ${old_instance_template_name} --region=${region} --format="value(properties.labels)")
        tags=$(gcloud compute instance-templates describe ${old_instance_template_name} --region=${region} --format="value(properties.tags.items)")
        metadata=$(gcloud compute instance-templates describe ${old_instance_template_name} --region=${region} --format="value(properties.metadata.items.value)")
        service_account=$(gcloud compute instance-templates describe ${old_instance_template_name} --region=${region} --format="value(properties.serviceAccounts.email)")
        scopes=$(gcloud compute instance-templates describe ${old_instance_template_name} --region=${region} --format="value(properties.serviceAccounts.scopes)")
        scopes=$(echo "$scopes" | sed "s/\[\|\]//g")
        scopes=$(echo "$scopes" | sed "s/ *', *'/,/g")
        scopes=$(echo "$scopes" | sed "s/^'//;s/'$//")
        echo "Variables initialised"
        gcloud compute instance-templates create ${template_name} \
        --instance-template-region=${region} \
        --machine-type=${machine_type} \
        --region=${region} \
        --network=${network} \
        --subnet=${subnetwork} \
        --create-disk=image=${latest_image_link},boot=yes,auto-delete=yes,device-name=persistent-disk-0,size=${disk_size},type=${disk_type},kms-key=${boot_disk_kms_key} \
        --tags=${tags} \
        --metadata=startup-script="${metadata}" \
        --service-account=${service_account} \
        --scopes=${scopes} \
        --reservation-affinity=any
        echo "Created Instance Template"
        new_instance_template_self_link=$(gcloud compute instance-templates describe ${template_name} --region=${region} --format="value(selfLink)")
        managed_instance_group=$(gcloud compute instance-groups managed list --sort-by=creationTimestamp --format="value(name)" --limit=1)
        gcloud compute instance-groups managed rolling-action start-update  ${managed_instance_group} --version template=${new_instance_template_self_link} --region=${region}
        echo "Rolling Update initiated with new instance template"
        gcloud compute instance-groups managed wait-until ${managed_instance_group} \
        --version-target-reached \
        --region=${region}
        echo "Instance group is stable"