name: Integration Test | Build Packer

# on:
#   push:
#     branches:
#       - main

on:
  pull_request:
    branches:
      - main

jobs:
  build_packer_workflow:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      PORT: ${{ secrets.PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      DROP_DB: ${{ secrets.DROP_DB}}
      TOPIC_VERIFY_EMAIL: ${{ secrets.TOPIC_VERIFY_EMAIL }}
      VERIFY_EMAIL_EXPIRY_MILLISECONDS: ${{ secrets.VERIFY_EMAIL_EXPIRY_MILLISECONDS }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setting up Postgres
      run: |
        sudo systemctl start postgresql.service

        sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_NAME }};"
        sudo -u postgres psql -c "CREATE USER ${{ secrets.DB_USERNAME }} WITH PASSWORD '${{ secrets.DB_PASSWORD }}';"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.DB_NAME }} TO ${{ secrets.DB_USERNAME }};"
    
    - name: Setup Logger Directory
      run: |
          sudo mkdir /var/log/csye6225
          echo "Logger directory created at /var/log/csye6225"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Deleting node_modules
      run: rm -r node_modules

    - name: Zipping webapp artifact
      run: cd ../ && zip -r webapp.zip webapp && cd - && cp ../webapp.zip .

    - name: Installing Packer
      run: sudo apt install -y packer
    
    - name: GCP Authentication
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: GCloud Info
      run: gcloud info

    - name: Setup 'packer'
      uses: hashicorp/setup-packer@main
      with:
        version: '1.10.1'

    - name: Packer Init
      run: packer init ./packer

    - name: Packer Build
      run: packer build -var 'proj_id=${{ secrets.GCP_PROJ_ID }}' -var 'db_username=${{ secrets.DB_USERNAME }}' -var 'db_password=${{ secrets.DB_PASSWORD }}' -var 'db_name=${{ secrets.DB_NAME }}' ./packer