name: Workflow-for-tests

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest

    env:
        PORT: ${{ secrets.PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_DIALECT: ${{ secrets.DB_DIALECT }}
        DROP_DB: ${{ secrets.DROP_DB}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Postgres
        run: |
            sudo apt update
            sudo apt install -y postgresql postgresql-contrib
            sudo systemctl start postgresql.service

            sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_NAME }};"
            sudo -u postgres psql -c "CREATE USER ${{ secrets.DB_USERNAME }} WITH PASSWORD '${{ secrets.DB_PASSWORD }}';"
            sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.DB_NAME }} TO ${{ secrets.DB_USERNAME}};"
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: npm install
      - name: Run tests
        run: npm run test
